// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'Button': typeof import('../components/Button.vue')['default'],
    'Chip': typeof import('../components/Chip.vue')['default'],
    'CircledDropdown': typeof import('../components/CircledDropdown.vue')['default'],
    'CompanyDetail': typeof import('../components/CompanyDetail.vue')['default'],
    'Content': typeof import('../components/Content.vue')['default'],
    'Divider': typeof import('../components/Divider.vue')['default'],
    'JobCard': typeof import('../components/JobCard.vue')['default'],
    'Loading': typeof import('../components/Loading.vue')['default'],
    'NotSelectedCompanyDetailState': typeof import('../components/NotSelectedCompanyDetailState.vue')['default'],
    'OtherPositionCard': typeof import('../components/OtherPositionCard.vue')['default'],
    'QualificationDescription': typeof import('../components/QualificationDescription.vue')['default'],
    'SearchWithMap': typeof import('../components/SearchWithMap.vue')['default'],
    'SideJobDetail': typeof import('../components/SideJobDetail.vue')['default'],
    'SideNavigation': typeof import('../components/SideNavigation.vue')['default'],
    'SideNavigationText': typeof import('../components/SideNavigationText.vue')['default'],
    'SpinnerLoading': typeof import('../components/SpinnerLoading.vue')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
